### ISSUE TITLE
python-Levenshtein-wheels problem bad solution link

### ISSUE THREAD

**Issue by chrisribe** [Azure/aaz-dev-tools#413]
This link is no longer valid: https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-levenshtein
in setup doc: 
https://github.com/Azure/aaz-dev-tools/edit/dev/docs/pages/usage/setup_and_run.md#install-tools-for-azure-cli-development

> 4.4 Possible problems
> For windows users, dependency python-levenshtein installation might run into trouble. developers might need to download [.whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-levenshtein) file and install it manually (reference to [link](https://stackoverflow.com/questions/37676623/cant-install-levenshtein-distance-package-on-windows-python-3-5/46414982))

This is preventing me from completing the setup on windows.

**Comment by chrisribe** [comment]
I re-setup in WSL and was getting the same issue. I found a workaround and wanted to share it here for reference.

**Cause:**
The latest setuptools adds a vendored wheel 0.43.0 and ignores wheel 0.30.0

**Workaround: (pin setuptools to 70.0.0)**
pip3 install setuptools==70.0.0

**Comment by chrisribe** [comment]
After re-testing this seems to fail still, will try and document the fix
```
Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Installing collected packages: sphinxcontrib-websupport, python-dateutil, pyproject-api, mccabe, MarkupSafe, jsbeautifier, jmespath, isort, isodate, iniconfig, imagesize, idna, gitdb, filelock, execnet, docutils, dill, deepdiff, colorama, charset-normalizer, chardet, cffi, certifi, cachetools, babel, astroid, argcomplete, alabaster, virtualenv, requests, pytest, pylint, knack, jinja2, gitpython, flake8, cryptography, tox, sphinx, requests-oauthlib, pytest-xdist, pytest-forked, azure-core, azure-cli-diff-tool, msrest, azure-multiapi-storage, azdev
ERROR: Exception:
Traceback (most recent call last):
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 457, in run
    installed = install_given_reqs(
                ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/req/__init__.py", line 70, in install_given_reqs
    requirement.install(
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 867, in install
    install_wheel(
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/operations/install/wheel.py", line 732, in install_wheel
    _install_wheel(
  File "/mnt/c/GitRepos/tools/AzureCLITools/env/lib/python3.12/site-packages/pip/_internal/operations/install/wheel.py", line 621, in _install_wheel
    assert os.path.exists(pyc_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by wangzelin007** [comment]
Hi @chrisribe 
I also created a WSL and I was able to execute it successfully, here are all the commands I used:
```
python -m venv env --prompt azcli
source env/bin/activate
pip install azdev -U
pip install --upgrade pip
pip install setuptools==70.0.0
azdev setup --cli ./azure-cli --repo ./azure-cli-extensions
```
![Image](https://github.com/user-attachments/assets/007402eb-e73c-4044-bad5-314c21607ace)
